# Generated by Django 5.2.15 on 2026-07-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone', models.CharField(max_length=15)),
                ('issue_description', models.TextField()),
                ('urgency', models.CharField(choices=[('LOW', 'Low (Minor leak)'), ('MEDIUM', 'Medium (Low pressure)'), ('HIGH', 'High (No water/Completely broken)')], default='MEDIUM', max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(help_text='Unique asset tag, e.g., HW-BHL-001', max_length=20, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=50, verbose_name='LGA')),
                ('state', models.CharField(default='Katsina', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('FUNCTIONAL', 'Functional (Green)'), ('MAINTENANCE', 'Needs Maintenance (Yellow)'), ('BROKEN', 'Broken Down (Red)')], default='FUNCTIONAL', max_length=15)),
                ('last_inspected', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100)),
                ('action_taken', models.TextField()),
                ('date_resolved', models.DateTimeField(auto_now_add=True)),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_log', to='hydrowatch.faultreport')),
            ],
        ),
        migrations.AddField(
            model_name='faultreport',
            name='water_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hydrowatch.waterpoint'),
        ),
    ]
