# Generated by Django 5.2.15 on 2026-07-03 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrowatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faultreport',
            name='is_paid_out',
            field=models.BooleanField(default=False, help_text='Has the technician been paid their net share?'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='platform_fee_community',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Your earnings from community processing', max_digits=10),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='platform_fee_technician',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Your earnings cut from the technician', max_digits=10),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='quoted_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total money paid by community', max_digits=10),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Technician Assigned'), ('FIXED', 'Repaired & Verified'), ('FAILED', 'Unresolved')], default='PENDING', max_length=15),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('lga_coverage', models.CharField(help_text='Local Government Area they service', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faultreport',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrowatch.technician'),
        ),
    ]
