# Generated by Django 5.2.15 on 2026-07-04 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrowatch', '0002_faultreport_created_at_faultreport_is_paid_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='user',
        ),
        migrations.AddField(
            model_name='technician',
            name='jobs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technician',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='technician',
            name='specialty',
            field=models.CharField(default='General Maintenance', max_length=100),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Technician Assigned'), ('FIXED', 'Repaired & Verified'), ('FAILED', 'Unresolved'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='technician',
            name='lga_coverage',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
