# Generated by Django 5.2.15 on 2026-07-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrowatch', '0003_remove_technician_user_technician_jobs_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancelog',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='cost_incurred',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='technician_name',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hydrowatch.faultreport'),
        ),
    ]
